### ISSUE TITLE
Zip with Windows release

### ISSUE THREAD

**Issue by cup** [merklecounty/rget#39]
i see here

https://github.com/merklecounty/rget/releases

that all releases are TAR.GZ, even Windows. This isnt a huge deal, as you can get tools to extract TAR.GZ on Windows. However to my knowledge they arent built in, even with Windows 10.

So it might make sense to offer ZIP builds instead to Windows users.

**Comment by philips** [comment]
Looks like I need to add this to https://github.com/merklecounty/rget/blob/master/.goreleaser.yml

If you have a moment would you mind creating a PR and testing

```
    # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    # Default is empty.
    format_overrides:
      - goos: windows
        format: zip
```

Via https://goreleaser.com/customization/
